'use strict';
const sounds=[{letter:'s',word:'sun',picture:'☀️'},{letter:'a',word:'apple',picture:'🍎'},{letter:'t',word:'tap',picture:'👆'},{letter:'p',word:'pig',picture:'🐷'},{letter:'i',word:'insect',picture:'🐞'},{letter:'n',word:'nest',picture:'🪺'}];
const words=[{word:'sat',picture:'🪑'},{word:'sit',picture:'🪑'},{word:'sip',picture:'🥤'},{word:'tap',picture:'👆'},{word:'tip',picture:'👉'},{word:'tin',picture:'🥫'},{word:'pin',picture:'📌'},{word:'pan',picture:'🍳'},{word:'pat',picture:'✋'},{word:'pit',picture:'🕳️'},{word:'nap',picture:'😴'},{word:'ant',picture:'🐜'}];
const vowels='aeiou';
let section=localStorage.getItem('phonika-section')||'learn',i=0,mode=localStorage.getItem('phonika-letter-mode')||'lower';
const $=id=>document.getElementById(id);const upper=()=>mode==='upper'||mode==='cursiveUpper',cursive=()=>mode.startsWith('cursive');
function textCase(s){return upper()?s.toUpperCase():s.toLowerCase();}
function coloredText(el,text){el.replaceChildren(...[...textCase(text)].map(ch=>{const span=document.createElement('span');span.textContent=ch;span.className=vowels.includes(ch.toLowerCase())?'vowel':'consonant';return span;}));}
function render(){const learning=section==='learn',list=learning?sounds:words,x=list[i%list.length];$('letter').hidden=!learning;$('readword').hidden=learning;if(learning){coloredText($('letter'),x.letter);$('letter').classList.toggle('cursive',cursive());}else{coloredText($('readword'),x.word);$('readword').classList.toggle('cursive',cursive());}$('picture').textContent=x.picture;$('picture').hidden=true;$('listen').hidden=false;$('mode').value=mode;$('learnTab').classList.toggle('on',learning);$('readTab').classList.toggle('on',!learning);$('dots').replaceChildren(...list.map((_,j)=>{const d=document.createElement('span');d.className='dot'+(j===i%list.length?' on':'');return d;}));}
function current(){const list=section==='learn'?sounds:words;return list[i%list.length];}
function speak(reveal=true){if(reveal){$('listen').hidden=true;$('picture').hidden=false;}if(!('speechSynthesis'in window))return;speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(current().word);u.lang='en-GB';u.rate=.72;u.pitch=1;speechSynthesis.speak(u);}
function switchSection(s){section=s;i=0;localStorage.setItem('phonika-section',section);if('speechSynthesis'in window)speechSynthesis.cancel();render();}
$('listen').onclick=()=>speak(true);$('picture').onclick=()=>speak(false);$('next').onclick=()=>{if('speechSynthesis'in window)speechSynthesis.cancel();const list=section==='learn'?sounds:words;i=(i+1)%list.length;render();};$('learnTab').onclick=()=>switchSection('learn');$('readTab').onclick=()=>switchSection('read');$('settingsOpen').onclick=()=>{$('settings').hidden=false;};$('settingsClose').onclick=()=>{$('settings').hidden=true;};$('settings').onclick=e=>{if(e.target===$('settings'))$('settings').hidden=true;};$('mode').onchange=e=>{mode=e.target.value;localStorage.setItem('phonika-letter-mode',mode);render();};render();