'use strict';
const l1=[{letter:'s',word:'sun',picture:'☀️'},{letter:'a',word:'apple',picture:'🍎'},{letter:'t',word:'tap',picture:'👆'},{letter:'p',word:'pig',picture:'🐷'},{letter:'i',word:'insect',picture:'🐞'},{letter:'n',word:'nest',picture:'🪺'}];
const l2=[{letter:'m',word:'map',picture:'🗺️'},{letter:'d',word:'dog',picture:'🐶'},{letter:'g',word:'goat',picture:'🐐'},{letter:'o',word:'orange',picture:'🍊'}];
const words1=[{word:'sat',picture:'🪑'},{word:'sit',picture:'🪑'},{word:'sip',picture:'🥤'},{word:'tap',picture:'👆'},{word:'tip',picture:'👉'},{word:'tin',picture:'🥫'},{word:'pin',picture:'📌'},{word:'pan',picture:'🍳'},{word:'pat',picture:'✋'},{word:'pit',picture:'🕳️'},{word:'nap',picture:'😴'},{word:'ant',picture:'🐜'}];
const words2=[{word:'mat',picture:'🧘'},{word:'map',picture:'🗺️'},{word:'man',picture:'👨'},{word:'mad',picture:'😠'},{word:'dog',picture:'🐶'},{word:'dig',picture:'⛏️'},{word:'dot',picture:'🔵'},{word:'got',picture:'🤲'},{word:'gap',picture:'↔️'},{word:'pot',picture:'🍲'},{word:'top',picture:'🔝'},{word:'mom',picture:'👩'},{word:'nod',picture:'🙂'},{word:'sad',picture:'😢'}];
const vowels='aeiou',SIZE=5,GOAL=3;
let level=Number(localStorage.getItem('phonika-level')||1),section=localStorage.getItem('phonika-section')||'learn',i=0,sessionCount=0,mode=localStorage.getItem('phonika-letter-mode')||'lower',marked=false;
let progress=JSON.parse(localStorage.getItem('phonika-letter-progress')||'{}');if(level!==1&&level!==2)level=1;
const $=id=>document.getElementById(id),cursive=()=>mode.startsWith('cursive');
function textCase(s){const lower=s.toLowerCase();if(mode==='upper'||mode==='cursiveUpper')return lower.toUpperCase();if(mode==='title'||mode==='cursiveTitle')return lower.charAt(0).toUpperCase()+lower.slice(1);return lower;}
function coloredText(el,text){el.replaceChildren(...[...textCase(text)].map(ch=>{const span=document.createElement('span');span.textContent=ch;span.className=vowels.includes(ch.toLowerCase())?'vowel':'consonant';return span;}));}
function score(ch){return Number(progress[ch]||0)}function mastered(ch){return score(ch)>=GOAL}
function introduced(){let n=2;if(mastered('m'))n=3;if(mastered('d')&&mastered('g'))n=4;return l2.slice(0,n);}
function learnList(){if(level===1)return l1.slice(0,5);const fresh=introduced();const reviews=l1.slice((fresh.length-2)%l1.length,(fresh.length-2)%l1.length+Math.max(1,SIZE-fresh.length));return [...reviews,...fresh].slice(0,SIZE);}
function readList(){if(level===1)return words1;const allowed=new Set([...l1,...introduced()].map(x=>x.letter));const a=[...words1,...words2].filter(x=>[...x.word].every(ch=>allowed.has(ch)));return a.length?a:words1;}
function list(){return section==='learn'?learnList():readList();}
function render(){const learning=section==='learn',items=list(),x=items[i%items.length];$('finish').hidden=true;$('practice').hidden=false;$('tabs').hidden=false;$('dots').hidden=false;$('bottom').hidden=false;$('brand').textContent='Phonika · Level '+level;$('level').value=String(level);$('letter').hidden=!learning;$('readword').hidden=learning;$('know').hidden=!learning;marked=false;$('know').disabled=false;$('know').classList.remove('done');if(learning){coloredText($('letter'),x.letter);$('letter').classList.toggle('cursive',cursive())}else{coloredText($('readword'),x.word);$('readword').classList.toggle('cursive',cursive())}$('picture').textContent=x.picture;$('picture').hidden=true;$('listen').hidden=false;$('mode').value=mode;$('learnTab').classList.toggle('on',learning);$('readTab').classList.toggle('on',!learning);$('dots').replaceChildren(...Array.from({length:SIZE},(_,j)=>{const d=document.createElement('span');d.className='dot'+(j===sessionCount?' on':'');return d}))}
function current(){const a=list();return a[i%a.length]}
function speak(reveal=true){if(reveal){$('listen').hidden=true;$('picture').hidden=false}if(!('speechSynthesis'in window))return;speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(current().word);u.lang='en-GB';u.rate=.72;speechSynthesis.speak(u)}
function markKnown(){if(section!=='learn'||marked)return;const ch=current().letter;progress[ch]=Math.min(GOAL,score(ch)+1);localStorage.setItem('phonika-letter-progress',JSON.stringify(progress));marked=true;$('know').disabled=true;$('know').classList.add('done')}
function start(){i=0;sessionCount=0;render()}function finish(){if('speechSynthesis'in window)speechSynthesis.cancel();$('practice').hidden=true;$('tabs').hidden=true;$('dots').hidden=true;$('bottom').hidden=true;$('finish').hidden=false}
function switchSection(s){section=s;localStorage.setItem('phonika-section',s);start()}function switchLevel(n){level=Number(n);localStorage.setItem('phonika-level',String(level));start()}
$('listen').onclick=()=>speak(true);$('picture').onclick=()=>speak(false);$('know').onclick=markKnown;$('next').onclick=()=>{sessionCount++;if(sessionCount>=SIZE){finish();return}const a=list();i=(i+1)%a.length;render()};$('continue').onclick=start;$('learnTab').onclick=()=>switchSection('learn');$('readTab').onclick=()=>switchSection('read');$('settingsOpen').onclick=()=>{$('settings').hidden=false};$('settingsClose').onclick=()=>{$('settings').hidden=true};$('settings').onclick=e=>{if(e.target===$('settings'))$('settings').hidden=true};$('level').onchange=e=>switchLevel(e.target.value);$('mode').onchange=e=>{mode=e.target.value;localStorage.setItem('phonika-letter-mode',mode);render()};start();